<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali</name>
   <tag></tag>
   <elementGuidId>16d94cec-dfb4-40ea-9c82-600c9be91f5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles_root__6_rRr.styles_medium__7QTIz.styles_transparent__ma0Kc.styles_primary__pVpF_.styles_btnModalStatusTrx__Hd0KY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ea0b670-3e13-4e3a-a684-15fcde5510cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_root__6_rRr styles_medium__7QTIz styles_transparent__ma0Kc styles_primary__pVpF_ styles_btnModalStatusTrx__Hd0KY</value>
      <webElementGuid>94677b95-ade0-47f8-9437-b8f9127fe7ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnBack</value>
      <webElementGuid>9808698f-8d2a-42f5-9ffa-6bab74cd84e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1cf2ce4-ca14-4241-b7de-6e234ad18968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>8017548d-41c1-4c39-b2c3-971b9cddf61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-r8-body&quot;)/div[@class=&quot;styles_btnModalStatusTrx__Hd0KY&quot;]/button[@class=&quot;styles_root__6_rRr styles_medium__7QTIz styles_transparent__ma0Kc styles_primary__pVpF_ styles_btnModalStatusTrx__Hd0KY&quot;]</value>
      <webElementGuid>366d9619-6006-4c14-98c0-c75acb535bf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>22ab711d-a257-4154-b511-19ad522624f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-r8-body']/div[4]/button</value>
      <webElementGuid>f846cc74-e170-462d-8b2e-d9003540e4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut Transaksi'])[1]/following::button[1]</value>
      <webElementGuid>bdbf0a56-bdb2-43b3-b20a-058b83f56811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usaha Mikro'])[1]/following::button[2]</value>
      <webElementGuid>f41fdf36-55de-44d3-9668-a8f700f3d807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>1c1e2321-5b07-49da-b921-d693a7791d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::button[1]</value>
      <webElementGuid>fe1533e8-70bf-446d-b5b2-bb8e0be399e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali']/parent::*</value>
      <webElementGuid>d47831da-ec5d-4749-9d7a-fcfcb1b74555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>f8a00790-7154-403c-a708-0c4eed24ae9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>65a12e3a-304f-4d07-8ad2-0176d9537d75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
