<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Usaha Mikro</name>
   <tag></tag>
   <elementGuidId>edc16222-b404-4bf4-9593-a7af36a7c131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-ra-body']/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b14231c-5b81-4f65-8ede-8fb6530670a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_label__nguRF</value>
      <webElementGuid>c9ce4353-5b88-412e-b515-60527099fae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Usaha Mikro</value>
      <webElementGuid>aa5fb084-0363-4b72-8f9b-76bf3f539ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-ra-body&quot;)/label[@class=&quot;styles_container__vdRpf&quot;]/span[@class=&quot;styles_label__nguRF&quot;]</value>
      <webElementGuid>31ff15b8-b65a-4f48-be47-508c106ae8f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-ra-body']/label[2]/span</value>
      <webElementGuid>432e4310-79dd-4719-afd1-a205033ee7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rumah Tangga'])[1]/following::span[2]</value>
      <webElementGuid>c786cc37-61d9-4117-bb9f-ce8968d8b57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK'])[1]/following::span[4]</value>
      <webElementGuid>1df41d75-2cb2-4523-afc8-35209f05a8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut Transaksi'])[1]/preceding::span[2]</value>
      <webElementGuid>edca257e-0f6e-43ea-a4f1-b8646aab5e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/preceding::span[2]</value>
      <webElementGuid>5e168da9-2709-44e4-8a08-1cf770c12536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Usaha Mikro']/parent::*</value>
      <webElementGuid>143c5a0f-7a6f-4933-a591-b81158a48803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>403610af-bede-4025-9690-3cfa52d82a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Usaha Mikro' or . = 'Usaha Mikro')]</value>
      <webElementGuid>020de3c4-687f-410f-b2f0-15d73d67b8e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
