<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Check_Alamat Usaha</name>
   <tag></tag>
   <elementGuidId>e1c03364-df55-4ff1-b555-4cf3a92bd2ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-r2q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-r2q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d5121f6-2032-4675-884d-987b3950bb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-r2q</value>
      <webElementGuid>601d9785-8b08-4e2e-af7c-f6b22559db76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c98a58d8-f09b-435b-8200-abb87e16754d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-1l7xo4v mantine-Checkbox-input</value>
      <webElementGuid>fb248ddb-61c0-4432-837f-edc7436d5672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-r2q&quot;)</value>
      <webElementGuid>a20986d1-9ce5-4761-9e2f-3d2f0ae8ea39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-r2q']</value>
      <webElementGuid>0393c23f-8cb0-423a-83d4-fee2f2ee0c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/div/div/div/div/div[2]/form/div[5]/div/div/div/input</value>
      <webElementGuid>d97a8ba8-1472-432c-afa2-5cbfccc490d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>192bf85e-8677-4963-aafb-1069b138a049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mantine-r2q' and @type = 'checkbox']</value>
      <webElementGuid>56592593-fead-4d6d-afae-1a62bc60b870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
