<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Unggah File</name>
   <tag></tag>
   <elementGuidId>60662d4a-4d0f-4bcb-a8dc-0291a5c062a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mantine-Dropzone-root.mantine-yxhxj7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-r2n-body']/ul/li[2]/div/span[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f076ee5f-3fe8-45eb-a239-7cf42f00d186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Dropzone-root mantine-yxhxj7</value>
      <webElementGuid>fc3f18af-9968-483f-b218-4c4f304a5dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>427f8c4c-5129-415c-bfd6-b414217e780d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cbd57304-f7ec-40b5-b706-6ec8047dea27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idle</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>471d3a8b-a3ca-415a-b94f-fe3f711467ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unggah File</value>
      <webElementGuid>59ee2015-8def-4b1d-a2b0-a0ff41762db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-r2n-body&quot;)/ul[@class=&quot;mantine-List-root mantine-1r6eud0&quot;]/li[@class=&quot;mantine-List-item mantine-5yyc8j&quot;]/div[@class=&quot;___ref-itemWrapper mantine-iwg4hh mantine-List-itemWrapper&quot;]/span[2]/div[@class=&quot;mantine-Dropzone-root mantine-yxhxj7&quot;]</value>
      <webElementGuid>eec377be-0990-499f-b47b-7488273a6fc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-r2n-body']/ul/li[2]/div/span[2]/div</value>
      <webElementGuid>88de552b-c005-4626-aa2d-971c340972b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kamera'])[1]/following::div[3]</value>
      <webElementGuid>af2e206c-1237-46fd-a620-5bb05a494d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Unggah foto'])[1]/following::div[6]</value>
      <webElementGuid>bdb8151e-f40d-46b9-9ca6-a88772ea5554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div</value>
      <webElementGuid>59c01a35-81ba-4d1f-a779-b9345ffec993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Unggah File' or . = 'Unggah File')]</value>
      <webElementGuid>0938d8e4-8595-4f2f-950b-59c97f9d2534</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
