<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Lengkap Pelanggan</name>
   <tag></tag>
   <elementGuidId>0659e498-6363-4d0f-aafd-3d540dd736f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'mantine-r18' and @placeholder = 'Nama Lengkap Pelanggan']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-r18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mantine-r18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91737aa7-84b3-4a7e-bdcf-c72a3971f863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Input-input mantine-TextInput-input mantine-f602jl</value>
      <webElementGuid>1b851343-7b93-4ca0-940b-43306f6e49b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-r18</value>
      <webElementGuid>ceb3f0af-4ecf-4593-9b36-1002c3e2470a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>880f472e-d444-425d-a7d7-fc36a8ccff5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-component</value>
      <webElementGuid>e35830bf-d100-4107-a0dc-91f3faa525ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1f9f4a72-04ed-4c9f-b16b-eef2b48f47db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lengkap Pelanggan</value>
      <webElementGuid>5e4c62af-ce0f-4e67-9e29-570ce4d23144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>733f4196-04a1-41af-93e5-82e42a42ba03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-r18&quot;)</value>
      <webElementGuid>9ffa5c16-8784-4254-b6d5-478bb61066c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-r18']</value>
      <webElementGuid>b99e30ea-9699-4239-8919-8e1a0c00d373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/div/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>8564195c-99e5-4544-a8d7-950ad9be783d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>35dff9ef-217d-4392-99eb-1fccfff43535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mantine-r18' and @placeholder = 'Nama Lengkap Pelanggan']</value>
      <webElementGuid>34693eee-fad9-499c-9219-84ac755d35aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
