<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat_alamat</name>
   <tag></tag>
   <elementGuidId>04f0d2ea-09a7-4289-9682-fd5f6e4ec376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-r1k</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='mantine-r1k']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>cbd0dfd3-f5d8-45f5-9822-043f2144fddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Input-input mantine-Textarea-input mantine-1okkfo7</value>
      <webElementGuid>b017556b-f9cc-4bc5-944b-65f4231a83d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-r1k</value>
      <webElementGuid>a5a3813b-8afd-4b34-b49a-1689892476eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm_editor</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>51d13dfb-482c-41db-933c-3e1a9d0bc186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>textareaComponent</value>
      <webElementGuid>95c0b720-f24e-45df-9d8d-dceeab66d5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c2036299-1078-4bda-ba2c-c7359484cea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>13f427f7-97e3-4373-bd8c-940f464f5808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan Alamat Sesuai KTP</value>
      <webElementGuid>87b76b10-5d96-48c0-a132-97dfb32d2a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2acfec1d-aa37-4033-95a3-6f622fce01bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-r1k&quot;)</value>
      <webElementGuid>71fe7923-656d-432c-b9b2-d4b1b81b7aa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='mantine-r1k']</value>
      <webElementGuid>30bdb7d6-ebc1-49a5-bdc6-f5782d4c6828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/div/div/div/div/div[2]/form/div[3]/div[5]/div/textarea</value>
      <webElementGuid>747e39ca-d72f-49f8-a7c0-9b49442dbdee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5f3e418e-cc75-49dc-89e1-492bf274bdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'mantine-r1k' and @name = 'alamat' and @placeholder = 'Masukkan Alamat Sesuai KTP']</value>
      <webElementGuid>4a6b0090-18c0-4389-960f-e48415ce01ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
