<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cek</name>
   <tag></tag>
   <elementGuidId>990f59f7-162d-4315-b1e7-c7e26ade2e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.styles_root__6_rRr.styles_medium__7QTIz.styles_contained__1kIDF.styles_primary__pVpF_.styles_btnBayar__o4O4A</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5712d3ec-2242-487b-8850-3551ada03565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_root__6_rRr styles_medium__7QTIz styles_contained__1kIDF styles_primary__pVpF_ styles_btnBayar__o4O4A</value>
      <webElementGuid>0886b86d-2444-48c0-8a85-e36922bf59a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnCheckNik</value>
      <webElementGuid>bdf57930-8f09-4b62-ac92-83940c11c5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>dd5849cd-c9ea-415a-aaad-f0e551c4d5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cek</value>
      <webElementGuid>cc5a039f-7545-426b-baa1-058f97c5f9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;mantine-AppShell-root mantine-1udmbix&quot;]/div[@class=&quot;mantine-hr6aor mantine-AppShell-body&quot;]/main[@class=&quot;mantine-18646eo mantine-AppShell-main&quot;]/div[@class=&quot;effect-1&quot;]/div[1]/div[@class=&quot;styles_innerContent__b1j3r styles_activeNavbar__pjnS8&quot;]/div[@class=&quot;mantine-Container-root styles_cardTop__99fsT mantine-d64fcd&quot;]/div[@class=&quot;mantine-Container-root styles_verifContainer__GY6kB mantine-d9zk78&quot;]/div[@class=&quot;styles_verifContainerDiv__bXQ4_&quot;]/div[@class=&quot;styles_formContainer__IXG1W&quot;]/form[1]/div[@class=&quot;styles_btnBayar__o4O4A&quot;]/button[@class=&quot;styles_root__6_rRr styles_medium__7QTIz styles_contained__1kIDF styles_primary__pVpF_ styles_btnBayar__o4O4A&quot;]</value>
      <webElementGuid>6cc12ca9-ffe6-43bf-a18a-5099023e3fd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>9aef72bf-ffe2-4d05-9a3a-829a2e1ebc35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/div/div/div/div[2]/div/div/form/div[2]/button</value>
      <webElementGuid>0599256f-2fe5-41ba-9bd1-38159bbe6633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan dan cek NIK pelanggan untuk melanjutkan transaksi LPG 3 Kg'])[1]/following::button[1]</value>
      <webElementGuid>7f7427b9-23ea-4bc6-ab64-a791dad114a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK KTP Pelanggan'])[1]/following::button[1]</value>
      <webElementGuid>55ab5cb0-b554-49c1-be0b-c660985bea2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelanggan Belum Terdaftar?'])[1]/preceding::button[1]</value>
      <webElementGuid>b517795b-8f28-49f0-b12c-34e2bd005d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftarkan Pelanggan Baru'])[1]/preceding::button[1]</value>
      <webElementGuid>4b2451d4-0da9-4f1c-97e6-04e4d839837f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cek']/parent::*</value>
      <webElementGuid>30df4c1c-f81c-4041-9962-26d2e6ca2c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>effb6ba5-7204-4f4a-8cd3-32adda63f840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Cek' or . = 'Cek')]</value>
      <webElementGuid>08be735b-9b95-41b8-a7ea-38f005b2fe36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
