<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Jenis Pengguna</name>
   <tag></tag>
   <elementGuidId>ca5be330-6cbc-4710-a00d-f5b00ae29b55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mantine-rr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mantine-rr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f8c49b5-6273-403a-9577-25d093019429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mantine-Input-input mantine-Select-input mantine-1k3rog5</value>
      <webElementGuid>d1d5bcf8-1bed-4935-b270-6f190fbccef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2e9bfa90-bb53-42f0-b97a-7d3a9f41ec2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>4b03edb6-273b-4606-bd10-2f976f339456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mantine-rr</value>
      <webElementGuid>d6a6528e-fcda-4657-9e27-41fe8f28394b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Jenis Pengguna</value>
      <webElementGuid>1940dc2c-e3aa-4b14-9c64-cdb43588807c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>0afe934e-53cc-4b6f-8087-a0074b93f4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mantine-stop-propagation</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>15e4de10-0da1-48c9-b114-0c4cc8f382e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d3ef93a-aed0-4abd-a711-dc1fbdd7448c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-rr&quot;)</value>
      <webElementGuid>6c74d31b-2fc0-45ad-b006-9c61dcd2329f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mantine-rr']</value>
      <webElementGuid>e6f586a5-0399-4841-9c64-5ade0e93c86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>cef037df-741b-4837-b999-18d1fde3949c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>6c72f1bc-6bd1-4d59-b32c-d51018f37b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'mantine-rr' and @placeholder = 'Pilih Jenis Pengguna']</value>
      <webElementGuid>59861343-bd43-4ac2-bcb7-05ba7e4ca4f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
