<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Melebihi Batas Kewajaran</name>
   <tag></tag>
   <elementGuidId>0ff052b1-04fe-48e1-b82f-c40106a00791</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-rk-body']/div/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6786d0be-db97-4104-8632-3c6b7c6552af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Melebihi Batas Kewajaran</value>
      <webElementGuid>bab8cbf5-bf3d-4460-a278-f21a94682a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-rk-body&quot;)/div[@class=&quot;styles_modalBody__9XWPC&quot;]/div[1]/h3[1]</value>
      <webElementGuid>766f477e-da21-4b29-8285-824a1807b550</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-rk-body']/div/div/h3</value>
      <webElementGuid>113ce9d4-58fc-482b-810b-2008c8777fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h3[1]</value>
      <webElementGuid>522345df-0c01-4b7e-8956-98b5b76ad466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::h3[1]</value>
      <webElementGuid>9995476a-7c22-48ae-aed0-83904a58c727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak dapat transaksi karena telah melebihi batas kewajaran pembelian LPG 3 kg bulan ini.'])[1]/preceding::h3[1]</value>
      <webElementGuid>2b704537-15d7-45a2-9d0b-b7a78b764951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oke'])[1]/preceding::h3[1]</value>
      <webElementGuid>17d6174f-f61a-4f06-ac50-459c58186418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Melebihi Batas Kewajaran']/parent::*</value>
      <webElementGuid>945bfeac-6061-4a2a-a8de-412a47fb30b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>78283e96-6059-42f3-81ea-69e9f83b1f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Melebihi Batas Kewajaran' or . = 'Melebihi Batas Kewajaran')]</value>
      <webElementGuid>d2a8fe75-c778-40ce-87f1-e1a46878c751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
