<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali</name>
   <tag></tag>
   <elementGuidId>70ddf41a-0668-4f2f-837a-0e6af2b26110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d7c9dcbb-870e-4c8b-bb0a-40b39a1e605a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styles_root__6_rRr styles_medium__7QTIz styles_outlined__khSXF styles_primary__pVpF_ </value>
      <webElementGuid>877274c2-2843-4396-abc2-8ab9443df4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>btnModalBack</value>
      <webElementGuid>cafa4ca3-1696-4258-89b1-082566c5ef38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>868b322c-c213-4e0a-b328-d8cbec38f2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kembali</value>
      <webElementGuid>af2e15fb-c0f4-40b5-902f-1fe083f38e64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-r7-body&quot;)/div[@class=&quot;styles_actionModal__LC0GL&quot;]/div[2]/button[@class=&quot;styles_root__6_rRr styles_medium__7QTIz styles_outlined__khSXF styles_primary__pVpF_&quot;]</value>
      <webElementGuid>3a80f1e7-bd58-4b8a-85a5-d0fda5de1249</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>2fe8546c-23ee-4d5b-888c-daf58b487a2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-r7-body']/div/div[2]/button</value>
      <webElementGuid>74536ea8-d34a-41d2-ad5b-d6b7088bd124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftarkan NIK'])[1]/following::button[1]</value>
      <webElementGuid>cc011251-5105-49c2-bfae-790e2196a3e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK pelanggan harus didaftarkan terlebih dahulu untuk dapat bertransaksi LPG Subsidi 3 KG.'])[1]/following::button[2]</value>
      <webElementGuid>89f1dc03-5358-42e8-ba3c-abc818202175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kembali']/parent::*</value>
      <webElementGuid>73fc88ad-23ec-4a21-82fc-5e8a4e5482fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div[2]/button</value>
      <webElementGuid>78d0c6f7-f30e-4328-905f-84cf9394f7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Kembali' or . = 'Kembali')]</value>
      <webElementGuid>a519045f-6c9e-470e-bfee-1d557669adac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
