<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_NIK belum terdaftar</name>
   <tag></tag>
   <elementGuidId>9f849baf-afd8-4036-aab7-bcd7841d0948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mantine-r7-body']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>9586348c-4fde-4819-b603-21e285cc1cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NIK belum terdaftar</value>
      <webElementGuid>8d9786e8-d285-44fb-959a-24158e6ae053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mantine-r7-body&quot;)/h4[1]</value>
      <webElementGuid>ef1502f5-83e2-4ed8-9536-573b60e6b4ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mantine-r7-body']/h4</value>
      <webElementGuid>d00367f0-aa57-4afb-830c-f6ce599218bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mantine-r7-body', '&quot;', ')/h4[1]')])[1]/following::h4[1]</value>
      <webElementGuid>8a065b4e-9c17-4018-b129-f67719b7f55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h4[1]</value>
      <webElementGuid>2ddd9996-8f59-41e5-80c1-ec90d27b1dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIK pelanggan harus didaftarkan terlebih dahulu untuk dapat bertransaksi LPG Subsidi 3 KG.'])[1]/preceding::h4[1]</value>
      <webElementGuid>87d29481-bb28-4414-ac99-2e2056ad234c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftarkan NIK'])[1]/preceding::h4[1]</value>
      <webElementGuid>a96ccdca-6e69-4528-bcc0-183a80691c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='NIK belum terdaftar']/parent::*</value>
      <webElementGuid>2c641da3-5ca6-436f-a699-cb810c07733b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>56ca81ae-940a-4e76-a288-3c7137add450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'NIK belum terdaftar' or . = 'NIK belum terdaftar')]</value>
      <webElementGuid>3f9b6fa0-3371-47fb-8934-563da985d968</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
