<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rumah TanggaOn Demand</name>
   <tag></tag>
   <elementGuidId>c9f751da-fb9b-46be-b28b-8b2bbbe58749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/main/div/div/div/div/div/div/div[2]/div/div[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ed56d466-16a8-4bd8-8ae9-62f3bb72294c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rumah TanggaOn Demand</value>
      <webElementGuid>0bff9062-aa21-4e63-ae29-43c3febfbf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;mantine-AppShell-root mantine-1udmbix&quot;]/div[@class=&quot;mantine-hr6aor mantine-AppShell-body&quot;]/main[@class=&quot;mantine-18646eo mantine-AppShell-main&quot;]/div[@class=&quot;effect-1&quot;]/div[1]/div[@class=&quot;styles_innerContent__b1j3r false&quot;]/div[@class=&quot;mantine-Container-root mantine-d64fcd&quot;]/div[@class=&quot;styles_pageContainer__XbfWc&quot;]/div[1]/div[@class=&quot;styles_container__o2Pb0&quot;]/div[@class=&quot;styles_infoPelangganSubsidi__83lX9&quot;]/div[@class=&quot;styles_containerCustomerInfo__N3jX5&quot;]/span[1]</value>
      <webElementGuid>9e6c51c8-6ca6-4edb-8883-36695e1faba2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/div/div/div/div/div/div[2]/div/div[4]/span</value>
      <webElementGuid>ffa49cae-8154-460a-a340-1ec4246b0e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Pengguna'])[1]/following::span[1]</value>
      <webElementGuid>348fef92-7cb0-4d2a-8c2d-b86a6bb23ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor NIK'])[1]/following::span[2]</value>
      <webElementGuid>8a2ebfc8-3bb0-4878-8f18-ef4ef16ca5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak dapat transaksi, stok tabung yang dapat dijual kosong. Silakan lakukan penebusan.'])[1]/preceding::span[3]</value>
      <webElementGuid>a7e976c6-6f4a-4f04-95c7-7eea9d27afd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rumah Tangga']/parent::*</value>
      <webElementGuid>666938a3-0c13-4fbe-bb74-35178a52f39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[4]/span</value>
      <webElementGuid>251dca84-5f9e-4ad0-bb3a-6ca6bd4a4c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rumah TanggaOn Demand' or . = 'Rumah TanggaOn Demand')]</value>
      <webElementGuid>b5277730-7ed6-406a-bc27-5d51690363f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
